# Generated by Django 3.0.5 on 2020-05-16 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='articl',
            fields=[
                ('idArt', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=250)),
                ('resumé', models.CharField(max_length=500)),
                ('dateEdition', models.DateField()),
                ('maison_ed', models.CharField(max_length=500)),
                ('nbd_cit', models.IntegerField()),
                ('keywords', models.CharField(max_length=500)),
                ('typeArticl', models.CharField(max_length=100)),
                ('path', models.FilePathField()),
            ],
        ),
        migrations.CreateModel(
            name='auteur',
            fields=[
                ('id_Chercheur', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('dateNais', models.DateField()),
                ('grade', models.CharField(max_length=100)),
                ('labo_affiliation', models.CharField(max_length=100)),
                ('domaine', models.CharField(max_length=100)),
                ('numTel', models.IntegerField()),
                ('adresse', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ecrit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordreAuteur', models.CharField(max_length=10)),
                ('auteurEcrit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstpage.auteur')),
            ],
        ),
    ]
